/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '12/16/18 7:41 PM' with Gradle 2.11
 *
 * @author james, @date 12/16/18 7:41 PM
 */
public class InstrumentationPretty {
    public boolean someLibraryMethod() {
        return true;
    }
}
