import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.apache.commons.cli.*;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'james' at '12/16/18 7:41 PM' with Gradle 2.11
 *
 * @author james, @date 12/16/18 7:41 PM
 */
public class InstrumentationPretty {

    private String outputpath;

    public InstrumentationPretty(String outputpath){
        this.outputpath = outputpath;
    }

    public void processInsturmentationOutput() throws IOException{
        //create test listener and parser
        XmlTestRunListener xmlTestListener = new XmlTestRunListener();
        HtmlTestRunListener htmlTestListener = new HtmlTestRunListener();
        InstrumentationResultParser parser = new InstrumentationResultParser("Instrumentation results", Arrays.asList(xmlTestListener, htmlTestListener));
        File reportDir = null;
        if(!this.outputpath.isEmpty()){
            reportDir = new File(outputpath);
        }else{
            //defaults to current directory/reports
            reportDir = new File(System.getProperty("user.dir") + "/reports");
        }
        reportDir.mkdir();
        xmlTestListener.setReportDir(reportDir);
        htmlTestListener.setReportDir(reportDir);
        List<String> lines = new ArrayList<String>();
        
        //read lines from STDIN 
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in)); 
        // Reading data using readLine 
        String input = null;
        while( (input = reader.readLine()) != null ){
            lines.add(input);
        }

        parser.processNewLines(lines.toArray(new String[0]));
        parser.done();
    }

    public static void main(String args[]){
        //process args
        Options options = new Options();

        Option output = new Option("o", "output", true, "output file path");
        output.setRequired(false);
        options.addOption(output);

        CommandLineParser parser = new DefaultParser();
        HelpFormatter formatter = new HelpFormatter();
        CommandLine cmd = null;

        try {
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            formatter.printHelp("InstrumentationPretty", options);
            System.exit(1);
        }

        String outputFilePath = cmd.getOptionValue("output");
        try {
            if(outputFilePath != null){
                new InstrumentationPretty(outputFilePath).processInsturmentationOutput();
            }else{
                new InstrumentationPretty("").processInsturmentationOutput();
            }        
        } catch (IOException e) {
            e.printStackTrace();
        }   
    }
}
