import org.junit.Test;
import org.omg.SendingContext.RunTime;

import static org.junit.Assert.*;

import java.io.File;
import java.io.IOException;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'james' at '12/16/18 7:41 PM' with Gradle 2.11
 *
 * @author james, @date 12/16/18 7:41 PM
 */
public class InstrumentationPrettyTest {
    @Test public void testXMLReportGeneration() throws IOException {
        InstrumentationPretty ip = new InstrumentationPretty("./src/test/resources/c6a3727a-0ab2-42e7-850d-10a2ba1be62c.txt");
        ip.processInsturmentationOutput();
        assertTrue("processInsturmentationOutput should generate a file ", new File("./reports/test_result_*.xml").exists());
    }
}
