import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'james' at '12/16/18 7:41 PM' with Gradle 2.11
 *
 * @author james, @date 12/16/18 7:41 PM
 */
public class InstrumentationPrettyTest {
    @Test public void testSomeLibraryMethod() {
        InstrumentationPretty ip = new InstrumentationPretty("src/test/resources/c6a3727a-0ab2-42e7-850d-10a2ba1be62c.txt");
        //assertTrue("someLibraryMethod should return 'true'", ip.someLibraryMethod());
    }
}
